CREATE TABLE IF NOT EXISTS student_department_transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  from_program_id BIGINT REFERENCES academic_programs(id) ON DELETE SET NULL,
  from_department_id BIGINT REFERENCES academic_departments(id) ON DELETE SET NULL,
  from_batch_id BIGINT REFERENCES academic_batches(id) ON DELETE SET NULL,
  from_semester_id BIGINT REFERENCES academic_semesters(id) ON DELETE SET NULL,
  to_program_id BIGINT REFERENCES academic_programs(id) ON DELETE SET NULL,
  to_department_id BIGINT REFERENCES academic_departments(id) ON DELETE SET NULL,
  to_batch_id BIGINT REFERENCES academic_batches(id) ON DELETE SET NULL,
  to_semester_id BIGINT REFERENCES academic_semesters(id) ON DELETE SET NULL,
  reason TEXT,
  effective_date DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_student_department_transfers_student_id
ON student_department_transfers(student_id);

CREATE INDEX IF NOT EXISTS idx_student_department_transfers_effective_date
ON student_department_transfers(effective_date);
