-- HR Enhancements: Attendance and Leaves

-- 1. Update hr_staff with additional fields
ALTER TABLE hr_staff 
ADD COLUMN IF NOT EXISTS joining_date DATE,
ADD COLUMN IF NOT EXISTS qualification VARCHAR(255),
ADD COLUMN IF NOT EXISTS date_of_birth DATE,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS blood_group VARCHAR(10),
ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(20);

-- 2. Staff Attendance table
CREATE TABLE IF NOT EXISTS hr_staff_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL REFERENCES hr_staff(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  status VARCHAR(20) NOT NULL, -- 'PRESENT', 'ABSENT', 'LEAVE', 'HALF_DAY'
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT uq_staff_date UNIQUE(staff_id, date)
);

CREATE INDEX IF NOT EXISTS idx_hr_staff_attendance_staff_id ON hr_staff_attendance(staff_id);
CREATE INDEX IF NOT EXISTS idx_hr_staff_attendance_date ON hr_staff_attendance(date);

-- 3. Leave Applications table
CREATE TABLE IF NOT EXISTS hr_leave_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id BIGINT NOT NULL REFERENCES hr_staff(id) ON DELETE CASCADE,
  leave_type VARCHAR(50) NOT NULL, -- 'CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'PATERNITY'
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- 'PENDING', 'APPROVED', 'REJECTED'
  reason TEXT,
  approved_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_leave_dates CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_hr_leave_applications_staff_id ON hr_leave_applications(staff_id);
CREATE INDEX IF NOT EXISTS idx_hr_leave_applications_status ON hr_leave_applications(status);

-- Triggers for updated_at
CREATE TRIGGER update_hr_staff_attendance_updated_at
BEFORE UPDATE ON hr_staff_attendance
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TRIGGER update_hr_leave_applications_updated_at
BEFORE UPDATE ON hr_leave_applications
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
