CREATE TABLE IF NOT EXISTS clc_certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
  certificate_no VARCHAR(50) NOT NULL UNIQUE,
  serial_no VARCHAR(50) NOT NULL UNIQUE,
  institute_name VARCHAR(150) NOT NULL DEFAULT 'Vikash Polytechnic, Bargarh',
  institute_location VARCHAR(150),
  affiliating_body VARCHAR(200),
  issue_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  date_of_admission DATE NOT NULL,
  date_of_leaving DATE NOT NULL,
  branch_name VARCHAR(150) NOT NULL,
  status_at_leaving VARCHAR(100) NOT NULL,
  reason_for_leaving TEXT NOT NULL,
  conduct VARCHAR(50) NOT NULL DEFAULT 'GOOD',
  student_name_snapshot VARCHAR(200) NOT NULL,
  father_guardian_name_snapshot VARCHAR(200),
  address_snapshot TEXT,
  dob_snapshot DATE,
  registration_number_snapshot VARCHAR(100),
  photo_url_snapshot TEXT,
  barcode_value VARCHAR(100),
  issued_by_staff_id BIGINT REFERENCES hr_staff(id) ON DELETE SET NULL,
  verified_by_staff_id BIGINT REFERENCES hr_staff(id) ON DELETE SET NULL,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_clc_certificates_date_range CHECK (date_of_leaving >= date_of_admission)
);

CREATE INDEX IF NOT EXISTS idx_clc_certificates_student_id ON clc_certificates(student_id);
CREATE INDEX IF NOT EXISTS idx_clc_certificates_issue_date ON clc_certificates(issue_date);
CREATE INDEX IF NOT EXISTS idx_clc_certificates_certificate_no ON clc_certificates(certificate_no);

CREATE TRIGGER update_clc_certificates_updated_at
BEFORE UPDATE ON clc_certificates
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
