-- Lookup enums
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'blood_group') THEN
    CREATE TYPE blood_group AS ENUM ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'UNKNOWN');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'admission_type') THEN
    CREATE TYPE admission_type AS ENUM ('HOSTELLER', 'DAY_SCHOLAR');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'address_type') THEN
    CREATE TYPE address_type AS ENUM ('PERMANENT', 'CURRENT');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'student_document_type') THEN
    CREATE TYPE student_document_type AS ENUM (
      '10TH_MARKSHEET',
      '12TH_MARKSHEET',
      'DIPLOMA_CERTIFICATE',
      'JEE_MARKSHEET',
      'OJEE_MARKSHEET',
      'INCOME_CERTIFICATE',
      'CASTE_CERTIFICATE',
      'RESIDENCE_CERTIFICATE',
      'OTHER'
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'exam_status') THEN
    CREATE TYPE exam_status AS ENUM ('SCHEDULED', 'ONGOING', 'COMPLETED', 'PUBLISHED');
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'weekday_code') THEN
    CREATE TYPE weekday_code AS ENUM ('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN');
  END IF;
END $$;

-- Academic
CREATE TABLE IF NOT EXISTS academic_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_academic_programs_code ON academic_programs(code);
CREATE TRIGGER update_academic_programs_updated_at
BEFORE UPDATE ON academic_programs
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS academic_departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  program_id BIGINT NOT NULL REFERENCES academic_programs(id) ON DELETE RESTRICT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_academic_departments_code ON academic_departments(code);
CREATE INDEX IF NOT EXISTS idx_academic_departments_program_id ON academic_departments(program_id);
CREATE TRIGGER update_academic_departments_updated_at
BEFORE UPDATE ON academic_departments
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS academic_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  program_id BIGINT NOT NULL REFERENCES academic_programs(id) ON DELETE RESTRICT,
  start_year INTEGER NOT NULL,
  end_year INTEGER NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_academic_batches_year_range CHECK (end_year >= start_year)
);

CREATE INDEX IF NOT EXISTS idx_academic_batches_program_id ON academic_batches(program_id);
CREATE TRIGGER update_academic_batches_updated_at
BEFORE UPDATE ON academic_batches
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS academic_semesters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_academic_semesters_code ON academic_semesters(code);
CREATE TRIGGER update_academic_semesters_updated_at
BEFORE UPDATE ON academic_semesters
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS academic_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_current BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_academic_sessions_date_range CHECK (end_date >= start_date)
);

CREATE TRIGGER update_academic_sessions_updated_at
BEFORE UPDATE ON academic_sessions
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- HR
CREATE TABLE IF NOT EXISTS hr_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  designation VARCHAR(100) NOT NULL,
  department_id BIGINT REFERENCES academic_departments(id) ON DELETE SET NULL,
  contact_number VARCHAR(20),
  email VARCHAR(100) NOT NULL UNIQUE,
  role VARCHAR(50) NOT NULL DEFAULT 'FACULTY',
  user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_hr_staff_department_id ON hr_staff(department_id);
CREATE INDEX IF NOT EXISTS idx_hr_staff_user_id ON hr_staff(user_id);
CREATE INDEX IF NOT EXISTS idx_hr_staff_email ON hr_staff(email);
CREATE TRIGGER update_hr_staff_updated_at
BEFORE UPDATE ON hr_staff
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Students
CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_number VARCHAR(100) UNIQUE,
  apaar_id VARCHAR(100) UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100),
  last_name VARCHAR(100) NOT NULL,
  dob DATE NOT NULL,
  photo_url TEXT,
  email VARCHAR(255),
  phone_number VARCHAR(20),
  blood_group blood_group DEFAULT 'UNKNOWN',
  admission_type admission_type NOT NULL DEFAULT 'DAY_SCHOLAR',
  program_id BIGINT REFERENCES academic_programs(id) ON DELETE SET NULL,
  department_id BIGINT REFERENCES academic_departments(id) ON DELETE SET NULL,
  batch_id BIGINT REFERENCES academic_batches(id) ON DELETE SET NULL,
  semester_id BIGINT REFERENCES academic_semesters(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_students_registration_number ON students(registration_number);
CREATE INDEX IF NOT EXISTS idx_students_apaar_id ON students(apaar_id);
CREATE INDEX IF NOT EXISTS idx_students_program_id ON students(program_id);
CREATE INDEX IF NOT EXISTS idx_students_department_id ON students(department_id);
CREATE INDEX IF NOT EXISTS idx_students_batch_id ON students(batch_id);
CREATE INDEX IF NOT EXISTS idx_students_semester_id ON students(semester_id);
CREATE TRIGGER update_students_updated_at
BEFORE UPDATE ON students
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS student_parents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL UNIQUE REFERENCES students(id) ON DELETE CASCADE,
  father_name VARCHAR(100),
  mother_name VARCHAR(100),
  guardian_name VARCHAR(100),
  father_photo_url TEXT,
  mother_photo_url TEXT,
  guardian_photo_url TEXT,
  income_certificate_url TEXT,
  caste_certificate_url TEXT,
  residence_certificate_url TEXT
);

CREATE TABLE IF NOT EXISTS student_addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  address_type address_type NOT NULL DEFAULT 'CURRENT',
  country VARCHAR(100) NOT NULL DEFAULT 'India',
  state VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  city VARCHAR(100),
  pincode VARCHAR(20) NOT NULL,
  address_line1 TEXT NOT NULL,
  address_line2 TEXT
);

CREATE INDEX IF NOT EXISTS idx_student_addresses_student_id ON student_addresses(student_id);

CREATE TABLE IF NOT EXISTS student_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  document_type student_document_type NOT NULL,
  file_url TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_student_documents_student_id ON student_documents(student_id);

-- Operations
CREATE TABLE IF NOT EXISTS operations_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  code VARCHAR(20) NOT NULL UNIQUE,
  department_id BIGINT NOT NULL REFERENCES academic_departments(id) ON DELETE RESTRICT,
  program_id BIGINT REFERENCES academic_programs(id) ON DELETE SET NULL,
  semester_id BIGINT REFERENCES academic_semesters(id) ON DELETE SET NULL,
  credits INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_operations_subjects_credits CHECK (credits >= 0)
);

CREATE INDEX IF NOT EXISTS idx_operations_subjects_code ON operations_subjects(code);
CREATE INDEX IF NOT EXISTS idx_operations_subjects_department_id ON operations_subjects(department_id);
CREATE TRIGGER update_operations_subjects_updated_at
BEFORE UPDATE ON operations_subjects
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS operations_timetables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  program_id BIGINT NOT NULL REFERENCES academic_programs(id) ON DELETE RESTRICT,
  department_id BIGINT NOT NULL REFERENCES academic_departments(id) ON DELETE RESTRICT,
  batch_id BIGINT NOT NULL REFERENCES academic_batches(id) ON DELETE RESTRICT,
  session_id BIGINT NOT NULL REFERENCES academic_sessions(id) ON DELETE RESTRICT,
  semester_id BIGINT NOT NULL REFERENCES academic_semesters(id) ON DELETE RESTRICT,
  section VARCHAR(10),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_operations_timetables_batch_id ON operations_timetables(batch_id);
CREATE TRIGGER update_operations_timetables_updated_at
BEFORE UPDATE ON operations_timetables
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS operations_timetable_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timetable_id BIGINT NOT NULL REFERENCES operations_timetables(id) ON DELETE CASCADE,
  day weekday_code NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  subject_id BIGINT REFERENCES operations_subjects(id) ON DELETE SET NULL,
  is_break BOOLEAN NOT NULL DEFAULT FALSE,
  break_name VARCHAR(50),
  room_no VARCHAR(20),
  faculty_id BIGINT REFERENCES hr_staff(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_operations_timetable_entries_time_range CHECK (end_time > start_time),
  CONSTRAINT chk_operations_timetable_entries_break_name CHECK (
    (is_break = TRUE AND break_name IS NOT NULL) OR
    (is_break = FALSE)
  )
);

CREATE INDEX IF NOT EXISTS idx_operations_timetable_entries_timetable_id ON operations_timetable_entries(timetable_id);
CREATE INDEX IF NOT EXISTS idx_operations_timetable_entries_subject_id ON operations_timetable_entries(subject_id);
CREATE TRIGGER update_operations_timetable_entries_updated_at
BEFORE UPDATE ON operations_timetable_entries
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS operations_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES operations_subjects(id) ON DELETE CASCADE,
  month DATE NOT NULL,
  attendance_data TEXT NOT NULL DEFAULT '',
  program_id BIGINT REFERENCES academic_programs(id) ON DELETE SET NULL,
  department_id BIGINT REFERENCES academic_departments(id) ON DELETE SET NULL,
  batch_id BIGINT REFERENCES academic_batches(id) ON DELETE SET NULL,
  semester_id BIGINT REFERENCES academic_semesters(id) ON DELETE SET NULL,
  session_id BIGINT REFERENCES academic_sessions(id) ON DELETE SET NULL,
  CONSTRAINT uq_student_subject_month UNIQUE (student_id, subject_id, month)
);

CREATE INDEX IF NOT EXISTS idx_operations_attendance_student_id ON operations_attendance(student_id);
CREATE INDEX IF NOT EXISTS idx_operations_attendance_subject_id ON operations_attendance(subject_id);
CREATE INDEX IF NOT EXISTS idx_operations_attendance_month ON operations_attendance(month);

-- Exams
CREATE TABLE IF NOT EXISTS academic_exams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  session_id BIGINT NOT NULL REFERENCES academic_sessions(id) ON DELETE RESTRICT,
  program_id BIGINT REFERENCES academic_programs(id) ON DELETE SET NULL,
  batch_id BIGINT REFERENCES academic_batches(id) ON DELETE SET NULL,
  semester_id BIGINT NOT NULL REFERENCES academic_semesters(id) ON DELETE RESTRICT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status exam_status NOT NULL DEFAULT 'SCHEDULED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_academic_exams_date_range CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_academic_exams_session_id ON academic_exams(session_id);
CREATE INDEX IF NOT EXISTS idx_academic_exams_semester_id ON academic_exams(semester_id);
CREATE TRIGGER update_academic_exams_updated_at
BEFORE UPDATE ON academic_exams
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS exam_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id BIGINT NOT NULL REFERENCES academic_exams(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  total_marks DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  secured_marks DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  percentage DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  sgpa DOUBLE PRECISION,
  cgpa DOUBLE PRECISION,
  result_status VARCHAR(20) NOT NULL DEFAULT 'PASS',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_exam_results_exam_id ON exam_results(exam_id);
CREATE INDEX IF NOT EXISTS idx_exam_results_student_id ON exam_results(student_id);
CREATE TRIGGER update_exam_results_updated_at
BEFORE UPDATE ON exam_results
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

CREATE TABLE IF NOT EXISTS exam_marks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id BIGINT NOT NULL REFERENCES academic_exams(id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES operations_subjects(id) ON DELETE RESTRICT,
  result_id BIGINT REFERENCES exam_results(id) ON DELETE CASCADE,
  marks_obtained DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  total_marks DOUBLE PRECISION NOT NULL DEFAULT 100.0,
  grade VARCHAR(20),
  grade_point DOUBLE PRECISION NOT NULL DEFAULT 0.0,
  is_absent BOOLEAN NOT NULL DEFAULT FALSE,
  remarks TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  CONSTRAINT chk_exam_marks_total_marks CHECK (total_marks >= 0),
  CONSTRAINT chk_exam_marks_marks_obtained CHECK (marks_obtained >= 0)
);

CREATE INDEX IF NOT EXISTS idx_exam_marks_exam_id ON exam_marks(exam_id);
CREATE INDEX IF NOT EXISTS idx_exam_marks_student_id ON exam_marks(student_id);
CREATE INDEX IF NOT EXISTS idx_exam_marks_subject_id ON exam_marks(subject_id);
CREATE INDEX IF NOT EXISTS idx_exam_marks_result_id ON exam_marks(result_id);
CREATE TRIGGER update_exam_marks_updated_at
BEFORE UPDATE ON exam_marks
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
